### ISSUE TITLE
The upstream website I use doesnt have a set host name

### ISSUE THREAD

**Issue by SuperBluw** [Darkseal/CORSflare#2]
Hi, just a question, The site I'm currently trying to proxy does not have a set host name, and for my use purposes, I'd like to not tinker around with the settings every day. I read there is a customizable GET parameter, but I'm a little illiterate in the case and have been trying to figure it out for a bit of time. Thank you for your time!

**Comment by Darkseal** [comment]
To use a variable hostname, just set `upstream_allow_override` to TRUE (to allow the default upstream to be overridden with a customizable GET parameter) and then you can do specify the hostname in the following way:

`https://my.proxy.url?CORSflare_upstream=<your_variable_hostname>`

If you're unable to implement that, you might want to seek professional help by hiring a developer that can deal with the proxy in the way you want: unfortunately we can't give such kind of support for free.

**Comment by SuperBluw** [comment]
Oh no, I can implement that easily, The instructions were just a little unclear for me, Thank you for taking your time to answer and have a good day!
