### ISSUE TITLE
Redirect handling

### ISSUE THREAD

**Issue by vadimkantorov** [Darkseal/CORSflare#6]
Does CORSflare support following basic redirects? e.g. the ones emitted by GitHub when downloading source code dumps: https://github.com/vadimkantorov/busyidetest/archive/refs/heads/master.zip

I can see in the code there is some redirect handling, so probably it's fine :) But if anyone can check, it would be awesome :)

Also, may be a good idea to add an explicit note about redirects to README :)

Thanks!

**Comment by Darkseal** [comment]
Yes, it should handle all standard 301/302/303/307/308 HTTP redirects (see code lines 245 and below).
