### ISSUE TITLE
Support of no pre-configured upstream?

### ISSUE THREAD

**Issue by vadimkantorov** [Darkseal/CORSflare#7]
Hi! Trying to understand, does CORSflare support CORS-proxying a user-provided URL? (or maybe limited to a list of domains?) as https://github.com/Zibri/cloudflare-cors-anywhere does

Thanks!

**Comment by Darkseal** [comment]
Hi there,

absolutely: see `upstream`, `upstream_mobile` and `upstream_path` parameters. As a matter of fact, it's the expected usage (selective upstream proxy).

**Comment by neilgandhi95** [comment]
Running into an issue here where some pages inject JS after page load, so unless the `upstream ` host is set to the same value in `upstream_get_parameter `, it won't load.

As an example, try setting `upstream_get_parameter ` to `retool.com`

Any ideas for solutions?
